name: menv

channels:
  - pyg
  - pytorch
  - anaconda
  - conda-forge
  - defaults

dependencies:
  - python=3.10.4
  - pip=22.2.2

  # Math and numerics
  - numba=0.56.4
  - numpy=1.23.3
  - scikit-learn=1.1.2
  - scipy=1.9.1

  # ML
  - pyg::pyg
  - pytorch::cudatoolkit=11.3
  - pytorch::pytorch==1.12.1
  - pytorch-lightning==1.7.6
  - pytorch::torchaudio==0.12.1
  - pytorch::torchvision==0.13.1
  - ogb
  - tensorboard==2.10.1
  - torchmetrics==0.10.2
  - wandb==0.13.4

  # Bio
  - biopython

  # Config
  - colorlog==6.7.0
  - hydra-core==1.2.0
  - omegaconf==2.2.3
  - pyyaml==6.0

  # Testing
  - icontract==2.6.1
  - pre-commit==2.20.0
  - pytest==7.1.3
  - typeguard==2.13.3

  # Other
  - filelock==3.8.0
  - protobuf==3.20.2
  - tqdm==4.64.1

  - pip:
      - hydra-colorlog==1.2.0
      - networkx==2.8.8
