# https://hydra.cc/docs/plugins/colorlog/
# enable color logging
#defaults:
#  - override hydra_logging: colorlog
#  - override job_logging: colorlog

# output directory, generated dynamically on each run
runtime:
  output_dir: ${paths.log_dir}
run:
  dir: ${paths.log_dir}/${task_name}/runs/${now:%Y-%m-%d}_${now:%H_%M}
sweep:
  dir: ${paths.log_dir}/${task_name}/multiruns/${now:%Y-%m-%d}_${now:%H_%M}
  subdir: ${hydra.job.num}

job_logging:
  handlers:
    file:
      class: logging.FileHandler
      formatter: simple
      filename: ${hydra.runtime.output_dir}/${hydra.job.name}.log
  root:
    level: INFO
    handlers: [console, file]
# https://github.com/facebookresearch/hydra/blob/main/hydra/conf/hydra/job_logging/default.yaml
