_target_: torch_geometric.transforms.compose.Compose
transforms:
  - _target_: transforms.degree_features.DegreeFeatures
    in_degree: True
  - _target_: transforms.degree_features.DegreeFeatures
    in_degree: False
