_target_: torch_geometric.transforms.compose.Compose
transforms:
  - _target_: transforms.col_zscore_features.ColZscoreFeatures
    attrs: [x]
  - _target_: transforms.sign_merged_features.SIGNMergedFeatures
    K: 4
  - _target_: transforms.binarize_targets.BinarizeTargets
    attrs: [y]
