_target_: torch.utils.data.dataset.ConcatDataset
datasets:
  - _target_: data.cluster_dbg_dataset.ClusteredDBGDataset
    root: ${paths.dataset_dir}/chm13_real_dataset/train
    transform: ${datamodules.transform}
    num_clusters: 8
  - _target_: data.dbg_dataset.DBGDataset
    root: ${paths.dataset_dir}/hg002_bed_dataset/train
    transform: ${datamodules.transform}
