train_path: ${paths.dataset_dir}/chr_11_homunculus_50M_01_02/train/${graph.type}
test_path: ${paths.dataset_dir}/chr_11_homunculus_50M_01_02/test/${graph.type}
val_path: ${paths.dataset_dir}/chr_11_homunculus_50M_01_02/val/${graph.type}
