train_path: ${paths.dataset_dir}/chr_homunculus_03_04/train/${graph.type}
test_path: ${paths.dataset_dir}/chr_homunculus_03_04/test/${graph.type}
val_path: ${paths.dataset_dir}/chr_homunculus_03_04/val/${graph.type}
