train_path: ${paths.dataset_dir}/${species_name}/train/${graph.type}
test_path: ${paths.dataset_dir}/${species_name}/test/${graph.type}
val_path: ${paths.dataset_dir}/${species_name}/val/${graph.type}
