defaults:
  - net: resgated_multidigraph
  - _self_

_target_: models.dbg_light_module.DBGLightningModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0
  #_target_: torch.optim.SGD
  #_partial_: true
  #lr: 0.001
  #momentum: 0.9

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.95
  patience: 2
  min_lr: 1.e-6
  verbose: True
  #_target_: torch.optim.lr_scheduler.CyclicLR
  #_partial_: True
  #mode: triangular
  #max_lr: 0.01
  #base_lr: 0.0001
  #step_size_up: 10
  #step_size_down: 20

criterion:
  #_target_: torch.nn.BCEWithLogitsLoss
  #pos_weight: # Use none for now, perhaps export this as metadata for dataset
  # _target_: torch.nn.MSELoss
  _target_: models.loss.focal_loss.FocalLoss
  alpha: 0.25
  gamma: 2
  reduction: mean
