# https://pytorch-lightning.readthedocs.io/en/latest/api/pytorch_lightning.callbacks.EarlyStopping.html

early_stopping:
  _target_: pytorch_lightning.callbacks.EarlyStopping
  monitor: "val/loss" # quantity to be monitored, must be specified !!!
  min_delta: 0.001 # minimum change in the monitored quantity to qualify as an improvement
  patience: 5 # number of checks with no improvement after which training will be stopped
  verbose: False # verbosity mode
  mode: "min" # "min" means metric needs to stop decreasing, "max" it needs to stop increasing
  strict: True # whether to crash the training if monitor is not found in the validation metrics
  check_finite: True # when set True, stops training when the monitor becomes NaN or infinite
  stopping_threshold: null # stop training immediately once the monitored quantity reaches this threshold
  divergence_threshold: null # stop training as soon as the monitored quantity becomes worse than this threshold
  check_on_train_epoch_end: null # whether to run early stopping at the end of the training epoch
