_target_: data.dbg_cluster_datamodule.DBGClusterDataModule
dataset_path: ${paths.dataset_dir}/${dataset_name}/
transform: null # transform_${graph}.yaml
save_dir: /tmp/metis
batch_size: 1
#num_workers: 4
