defaults:
  - _self_
  - datasets@train_datasets: concat_datasets_train.yaml
  - datasets@val_datasets: concat_datasets_val.yaml
  - transform: tf_pe_zscore_bin.yaml

_target_: data.combined_dbg_datamodule.CombinedDBGDataModule
batch_size: 1
num_workers: 4
num_clusters: 8
