# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - hydra: hydra.yaml
  - loggers: loggers.yaml
  - paths: paths.yaml
  - datamodules: datamodules.yaml
  - models: models.yaml
  - trainer: trainer.yaml
  - experiment: null
  - _self_

# task name, used as output directory path
task_name: "inference"

# Id of the model training task
train_id: #
# path of model to use for inference
model_path: ${paths.storage_dir}/models/${baseline}/${train_id}/best_model.ckpt
# dataset_name and baseline are defined in experiment
loggers:
  wandb:
    name: inference_${dataset_name}
    group: inference_${baseline}_T${models.offset}
    tags: ["resgated_mdg"]
    offline: true
