# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - hydra: hydra.yaml
  - loggers: loggers.yaml
  - paths: paths.yaml
  - datamodules: datamodules_regression.yaml
  - models: models_regression.yaml
  - trainer: trainer.yaml
  - experiment@_here_: lja_inference.yaml
  - _self_

# task name, used as output directory path
task_name: "inference"

lja_mode: true

# Id of the model training task
train_id: #
# dataset_name and baseline are defined in experiment
loggers:
  wandb:
    name: inference_${dataset_name}
    group: inference_${baseline}_T${models.threshold}
    tags: ["resgated_mdg"]
    offline: true
