# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - hydra: hydra.yaml
  - loggers: loggers.yaml
  - paths: paths.yaml
  - callbacks: callbacks.yaml
  - datamodules: combined_datamodules.yaml
  - models: models_regression.yaml
  - trainer: trainer_gpu.yaml
  - experiment: null
  - _self_

# task name, used as output directory path
task_name: "train"
metadata:
  graph: multidigraph

# dataset_name and baseline are defined in experiment config
loggers:
  wandb:
    name: train_r_${dataset_name}
    group: train_r_${baseline}
    tags: ["resgated_mdg", "combined_datasets", "regression"]

#use False to skip if we should only do the testing
train: true

# evaluation on the test data
test: false

# we can provide previously trained model here
ckpt_path: null
# unique identifier of trainining run
train_id: ${now:%y%m%d%H%M}
# dir where do we want to store the best model?
model_output_path: ${paths.storage_dir}/models/regress_models/${baseline}/${train_id}/
