# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
# the graph needs to be in list after datatransforms config in order to be visible
defaults:
  - hydra: hydra.yaml
  - loggers: loggers.yaml
  - paths: paths.yaml
  - experiment: null
  - datamodules@datatransforms: datatransforms
  - graph: null # specify using command line args [digraph | multidigraph]
  - _self_

species_name: null
# task name, used as output directory path
task_name: "transform"
# custom configs
