PROJECT_ROOT=./ python src/transform.py graph=multidigraph species_name=chr_1_real_04_30
PROJECT_ROOT=./ python src/transform.py graph=multidigraph species_name=chr_2_real_04_30
PROJECT_ROOT=./ python src/transform.py graph=multidigraph species_name=chr_3_real_04_30
PROJECT_ROOT=./ python src/transform.py graph=multidigraph species_name=chr_4_real_04_30
PROJECT_ROOT=./ python src/transform.py graph=multidigraph species_name=chr_5_real_04_30
#PROJECT_ROOT=./ python src/transform.py graph=multidigraph species_name=chr_6_real_04_30
PROJECT_ROOT=./ python src/transform.py graph=multidigraph species_name=chr_6_real_06_06
PROJECT_ROOT=./ python src/transform.py graph=multidigraph species_name=chr_7_real_04_30
PROJECT_ROOT=./ python src/transform.py graph=multidigraph species_name=chr_8_real_04_30
PROJECT_ROOT=./ python src/transform.py graph=multidigraph species_name=chr_9_real_04_30
PROJECT_ROOT=./ python src/transform.py graph=multidigraph species_name=chr_10_real_04_30
PROJECT_ROOT=./ python src/transform.py graph=multidigraph species_name=chr_11_real_04_30
PROJECT_ROOT=./ python src/transform.py graph=multidigraph species_name=chr_12_real_04_30
PROJECT_ROOT=./ python src/transform.py graph=multidigraph species_name=chr_13_real_04_30
PROJECT_ROOT=./ python src/transform.py graph=multidigraph species_name=chr_14_real_04_30
PROJECT_ROOT=./ python src/transform.py graph=multidigraph species_name=chr_15_real_04_30
PROJECT_ROOT=./ python src/transform.py graph=multidigraph species_name=chr_16_real_05_01
PROJECT_ROOT=./ python src/transform.py graph=multidigraph species_name=chr_17_real_05_01
PROJECT_ROOT=./ python src/transform.py graph=multidigraph species_name=chr_18_real_04_29
PROJECT_ROOT=./ python src/transform.py graph=multidigraph species_name=chr_19_real_04_29
PROJECT_ROOT=./ python src/transform.py graph=multidigraph species_name=chr_20_real_05_01
#PROJECT_ROOT=./ python src/transform.py graph=multidigraph species_name=chr_21_real_05_01
#PROJECT_ROOT=./ python src/transform.py graph=multidigraph species_name=chr_22_real_05_01
PROJECT_ROOT=./ python src/transform.py graph=multidigraph species_name=chr_21_real_06_06
PROJECT_ROOT=./ python src/transform.py graph=multidigraph species_name=chr_22_real_06_07
PROJECT_ROOT=./ python src/transform.py graph=multidigraph species_name=chr_X_real_05_01
